changesDir: .changes
unreleasedDir: unreleased
changelogPath: CHANGELOG.md
headerPath: header.md
versionExt: md
versionFormat: '## {{.Version}}'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}} ([#{{.Custom.Issue}}](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/{{.Custom.Issue}}))'
newlines:
  afterChangelogHeader: 1
  beforeChangelogVersion: 1
  endOfVersion: 1
kinds:
  - key: breaking
    label: Breaking changes
    auto: major
  - key: added
    label: Features
    auto: minor
  - key: fixed
    label: Fixes
    auto: patch
  - key: security
    label: Security
    auto: patch
  - key: internal
    label: Internal changes
    auto: none
body:
  minLength: 10
custom:
  - key: Issue
    label: GitHub issue or PR number
    type: int
    minInt: 1
