# Java 8
language: java
jdk: openjdk8

# Cache Maven dependencies for faster builds and less spam in the logs
cache:
  directories:
  - "$HOME/.m2"

# Give up sudo to enable container-based builds
sudo: false

# Prevent separate install step
# (Travis would run mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V prior to the test build)
install: true

# Only send mails if a build fails
notifications:
  email:
    on_success: never
    on_failure: always

# Deployment and publishing settings
env:
  global:
  - GPG_DIR="`pwd`/deploy"

after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPT_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPT_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
- chmod +x "$GPG_DIR/publish.sh"
- "$GPG_DIR/publish.sh"
