package com.github.theholywaffle.teamspeak3.api;

/**
 * Known permission names. Availability and numeric IDs are supplied by the connected server.
 * Use the string APIs for permissions added by a newer server.
 */
public enum IPermissionType {

	I_CHANNEL_MIN_DEPTH("i_channel_min_depth", "Min channel creation depth in hierarchy"),
	I_CHANNEL_MAX_DEPTH("i_channel_max_depth", "Max channel creation depth in hierarchy"),
	I_CHANNEL_PERMISSION_MODIFY_POWER("i_channel_permission_modify_power", "Modify channel permission power"),
	I_CHANNEL_NEEDED_PERMISSION_MODIFY_POWER("i_channel_needed_permission_modify_power", "Needed modify channel permission power"),
	I_CHANNEL_CREATE_MODIFY_WITH_CODEC_MAXQUALITY("i_channel_create_modify_with_codec_maxquality", "Create channels with custom codec quality"),
	I_CHANNEL_CREATE_MODIFY_WITH_CODEC_LATENCY_FACTOR_MIN("i_channel_create_modify_with_codec_latency_factor_min", "Create channels with minimal custom codec latency factor"),
	I_CHANNEL_CREATE_MODIFY_WITH_TEMP_DELETE_DELAY("i_channel_create_modify_with_temp_delete_delay", "Max delete delay for temporary channels"),
	I_CHANNEL_MODIFY_POWER("i_channel_modify_power", "Channel modify power"),
	I_CHANNEL_NEEDED_MODIFY_POWER("i_channel_needed_modify_power", "Needed channel modify power"),
	I_CHANNEL_DELETE_POWER("i_channel_delete_power", "Delete channel power"),
	I_CHANNEL_NEEDED_DELETE_POWER("i_channel_needed_delete_power", "Needed delete channel power"),
	I_CHANNEL_JOIN_POWER("i_channel_join_power", "Channel join power"),
	I_CHANNEL_NEEDED_JOIN_POWER("i_channel_needed_join_power", "Needed channel join power"),
	I_CHANNEL_SUBSCRIBE_POWER("i_channel_subscribe_power", "Channel subscribe power"),
	I_CHANNEL_NEEDED_SUBSCRIBE_POWER("i_channel_needed_subscribe_power", "Needed channel subscribe power"),
	I_CHANNEL_DESCRIPTION_VIEW_POWER("i_channel_description_view_power", "Channel description view power"),
	I_CHANNEL_NEEDED_DESCRIPTION_VIEW_POWER("i_channel_needed_description_view_power", "Needed channel needed description view power"),
	I_ICON_ID("i_icon_id", "Group icon identifier"),
	I_MAX_ICON_FILESIZE("i_max_icon_filesize", "Max icon filesize in bytes"),
	I_GROUP_AUTO_UPDATE_TYPE("i_group_auto_update_type", "Group auto-update type"),
	I_GROUP_AUTO_UPDATE_MAX_VALUE("i_group_auto_update_max_value", "Group auto-update max value"),
	I_GROUP_SORT_ID("i_group_sort_id", "Group sort id"),
	I_GROUP_SHOW_NAME_IN_TREE("i_group_show_name_in_tree", "Show group name in tree depending on selected mode"),
	I_GROUP_MODIFY_POWER("i_group_modify_power", "Group modify power"),
	I_GROUP_NEEDED_MODIFY_POWER("i_group_needed_modify_power", "Needed group modify power"),
	I_GROUP_MEMBER_ADD_POWER("i_group_member_add_power", "Group member add power"),
	I_GROUP_NEEDED_MEMBER_ADD_POWER("i_group_needed_member_add_power", "Needed group member add power"),
	I_GROUP_MEMBER_REMOVE_POWER("i_group_member_remove_power", "Group member delete power"),
	I_GROUP_NEEDED_MEMBER_REMOVE_POWER("i_group_needed_member_remove_power", "Needed group member delete power"),
	I_PERMISSION_MODIFY_POWER("i_permission_modify_power", "Permission modify power"),
	I_CLIENT_PERMISSION_MODIFY_POWER("i_client_permission_modify_power", "Client permission modify power"),
	I_CLIENT_NEEDED_PERMISSION_MODIFY_POWER("i_client_needed_permission_modify_power", "Needed client permission modify power"),
	I_CLIENT_MAX_CLONES_UID("i_client_max_clones_uid", "Max additional connections per client identity"),
	I_CLIENT_MAX_IDLETIME("i_client_max_idletime", "Max idle time in seconds"),
	I_CLIENT_MAX_AVATAR_FILESIZE("i_client_max_avatar_filesize", "Max avatar filesize in bytes"),
	I_CLIENT_MAX_CHANNEL_SUBSCRIPTIONS("i_client_max_channel_subscriptions", "Max channel subscriptions"),
	I_CLIENT_SERVERQUERY_VIEW_POWER("i_client_serverquery_view_power", "ServerQuery view power"),
	I_CLIENT_NEEDED_SERVERQUERY_VIEW_POWER("i_client_needed_serverquery_view_power", "Needed ServerQuery view power"),
	I_CLIENT_KICK_FROM_SERVER_POWER("i_client_kick_from_server_power", "Client kick power from server"),
	I_CLIENT_NEEDED_KICK_FROM_SERVER_POWER("i_client_needed_kick_from_server_power", "Needed client kick power from server"),
	I_CLIENT_KICK_FROM_CHANNEL_POWER("i_client_kick_from_channel_power", "Client kick power from channel"),
	I_CLIENT_NEEDED_KICK_FROM_CHANNEL_POWER("i_client_needed_kick_from_channel_power", "Needed client kick power from channel"),
	I_CLIENT_BAN_POWER("i_client_ban_power", "Client ban power"),
	I_CLIENT_NEEDED_BAN_POWER("i_client_needed_ban_power", "Needed client ban power"),
	I_CLIENT_MOVE_POWER("i_client_move_power", "Client move power"),
	I_CLIENT_NEEDED_MOVE_POWER("i_client_needed_move_power", "Needed client move power"),
	I_CLIENT_COMPLAIN_POWER("i_client_complain_power", "Complain power"),
	I_CLIENT_NEEDED_COMPLAIN_POWER("i_client_needed_complain_power", "Needed complain power"),
	I_CLIENT_BAN_MAX_BANTIME("i_client_ban_max_bantime", "Max bantime"),
	I_CLIENT_PRIVATE_TEXTMESSAGE_POWER("i_client_private_textmessage_power", "Client private message power"),
	I_CLIENT_NEEDED_PRIVATE_TEXTMESSAGE_POWER("i_client_needed_private_textmessage_power", "Needed client private message power"),
	I_CLIENT_TALK_POWER("i_client_talk_power", "Client talk power"),
	I_CLIENT_NEEDED_TALK_POWER("i_client_needed_talk_power", "Needed client talk power"),
	I_CLIENT_POKE_POWER("i_client_poke_power", "Client poke power"),
	I_CLIENT_NEEDED_POKE_POWER("i_client_needed_poke_power", "Needed client poke power"),
	I_CLIENT_WHISPER_POWER("i_client_whisper_power", "Client whisper power"),
	I_CLIENT_NEEDED_WHISPER_POWER("i_client_needed_whisper_power", "Client needed whisper power"),
	I_FT_FILE_UPLOAD_POWER("i_ft_file_upload_power", "File upload power"),
	I_FT_NEEDED_FILE_UPLOAD_POWER("i_ft_needed_file_upload_power", "Needed file upload power"),
	I_FT_FILE_DOWNLOAD_POWER("i_ft_file_download_power", "File download power"),
	I_FT_NEEDED_FILE_DOWNLOAD_POWER("i_ft_needed_file_download_power", "Needed file download power"),
	I_FT_FILE_DELETE_POWER("i_ft_file_delete_power", "File delete power"),
	I_FT_NEEDED_FILE_DELETE_POWER("i_ft_needed_file_delete_power", "Needed file delete power"),
	I_FT_FILE_RENAME_POWER("i_ft_file_rename_power", "File rename power"),
	I_FT_NEEDED_FILE_RENAME_POWER("i_ft_needed_file_rename_power", "Needed file rename power"),
	I_FT_FILE_BROWSE_POWER("i_ft_file_browse_power", "File browse power"),
	I_FT_NEEDED_FILE_BROWSE_POWER("i_ft_needed_file_browse_power", "Needed file browse power"),
	I_FT_DIRECTORY_CREATE_POWER("i_ft_directory_create_power", "Create directory power"),
	I_FT_NEEDED_DIRECTORY_CREATE_POWER("i_ft_needed_directory_create_power", "Needed create directory power"),
	I_FT_QUOTA_MB_DOWNLOAD_PER_CLIENT("i_ft_quota_mb_download_per_client", "Download quota per client in MByte"),
	I_FT_QUOTA_MB_UPLOAD_PER_CLIENT("i_ft_quota_mb_upload_per_client", "Upload quota per client in MByte"),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_HELP_VIEW("i_needed_modify_power_serverinstance_help_view", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_INFO_VIEW("i_needed_modify_power_serverinstance_info_view", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_VIRTUALSERVER_LIST("i_needed_modify_power_serverinstance_virtualserver_list", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_BINDING_LIST("i_needed_modify_power_serverinstance_binding_list", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_PERMISSION_LIST("i_needed_modify_power_serverinstance_permission_list", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_PERMISSION_FIND("i_needed_modify_power_serverinstance_permission_find", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CREATE("i_needed_modify_power_virtualserver_create", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_DELETE("i_needed_modify_power_virtualserver_delete", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_START_ANY("i_needed_modify_power_virtualserver_start_any", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_STOP_ANY("i_needed_modify_power_virtualserver_stop_any", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CHANGE_MACHINE_ID("i_needed_modify_power_virtualserver_change_machine_id", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CHANGE_TEMPLATE("i_needed_modify_power_virtualserver_change_template", ""),
	I_NEEDED_MODIFY_POWER_SERVERQUERY_LOGIN("i_needed_modify_power_serverquery_login", ""),
	I_NEEDED_MODIFY_POWER_SERVERQUERY_LOGIN_CREATE("i_needed_modify_power_serverquery_login_create", ""),
	I_NEEDED_MODIFY_POWER_SERVERQUERY_LOGIN_DELETE("i_needed_modify_power_serverquery_login_delete", ""),
	I_NEEDED_MODIFY_POWER_SERVERQUERY_LOGIN_LIST("i_needed_modify_power_serverquery_login_list", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_TEXTMESSAGE_SEND("i_needed_modify_power_serverinstance_textmessage_send", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_LOG_VIEW("i_needed_modify_power_serverinstance_log_view", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_LOG_ADD("i_needed_modify_power_serverinstance_log_add", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_STOP("i_needed_modify_power_serverinstance_stop", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_MODIFY_SETTINGS("i_needed_modify_power_serverinstance_modify_settings", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_MODIFY_QUERYGROUP("i_needed_modify_power_serverinstance_modify_querygroup", ""),
	I_NEEDED_MODIFY_POWER_SERVERINSTANCE_MODIFY_TEMPLATES("i_needed_modify_power_serverinstance_modify_templates", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_SELECT("i_needed_modify_power_virtualserver_select", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_INFO_VIEW("i_needed_modify_power_virtualserver_info_view", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CONNECTIONINFO_VIEW("i_needed_modify_power_virtualserver_connectioninfo_view", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CHANNEL_LIST("i_needed_modify_power_virtualserver_channel_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CHANNEL_SEARCH("i_needed_modify_power_virtualserver_channel_search", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CLIENT_LIST("i_needed_modify_power_virtualserver_client_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CLIENT_SEARCH("i_needed_modify_power_virtualserver_client_search", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CLIENT_DBLIST("i_needed_modify_power_virtualserver_client_dblist", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CLIENT_DBSEARCH("i_needed_modify_power_virtualserver_client_dbsearch", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CLIENT_DBINFO("i_needed_modify_power_virtualserver_client_dbinfo", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_PERMISSION_FIND("i_needed_modify_power_virtualserver_permission_find", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CUSTOM_SEARCH("i_needed_modify_power_virtualserver_custom_search", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_START("i_needed_modify_power_virtualserver_start", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_STOP("i_needed_modify_power_virtualserver_stop", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_TOKEN_LIST("i_needed_modify_power_virtualserver_token_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_TOKEN_ADD("i_needed_modify_power_virtualserver_token_add", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_TOKEN_USE("i_needed_modify_power_virtualserver_token_use", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_TOKEN_DELETE("i_needed_modify_power_virtualserver_token_delete", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_APIKEY_ADD("i_needed_modify_power_virtualserver_apikey_add", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_APIKEY_MANAGE("i_needed_modify_power_virtualserver_apikey_manage", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_LOG_VIEW("i_needed_modify_power_virtualserver_log_view", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_LOG_ADD("i_needed_modify_power_virtualserver_log_add", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_JOIN_IGNORE_PASSWORD("i_needed_modify_power_virtualserver_join_ignore_password", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_NOTIFY_REGISTER("i_needed_modify_power_virtualserver_notify_register", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_NOTIFY_UNREGISTER("i_needed_modify_power_virtualserver_notify_unregister", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_SNAPSHOT_CREATE("i_needed_modify_power_virtualserver_snapshot_create", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_SNAPSHOT_DEPLOY("i_needed_modify_power_virtualserver_snapshot_deploy", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_PERMISSION_RESET("i_needed_modify_power_virtualserver_permission_reset", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_NAME("i_needed_modify_power_virtualserver_modify_name", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_WELCOMEMESSAGE("i_needed_modify_power_virtualserver_modify_welcomemessage", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_MAXCLIENTS("i_needed_modify_power_virtualserver_modify_maxclients", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_RESERVED_SLOTS("i_needed_modify_power_virtualserver_modify_reserved_slots", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_PASSWORD("i_needed_modify_power_virtualserver_modify_password", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_DEFAULT_SERVERGROUP("i_needed_modify_power_virtualserver_modify_default_servergroup", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_DEFAULT_CHANNELGROUP("i_needed_modify_power_virtualserver_modify_default_channelgroup", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_DEFAULT_CHANNELADMINGROUP("i_needed_modify_power_virtualserver_modify_default_channeladmingroup", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_CHANNEL_FORCED_SILENCE("i_needed_modify_power_virtualserver_modify_channel_forced_silence", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_COMPLAIN("i_needed_modify_power_virtualserver_modify_complain", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_ANTIFLOOD("i_needed_modify_power_virtualserver_modify_antiflood", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_FT_SETTINGS("i_needed_modify_power_virtualserver_modify_ft_settings", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_FT_QUOTAS("i_needed_modify_power_virtualserver_modify_ft_quotas", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_HOSTMESSAGE("i_needed_modify_power_virtualserver_modify_hostmessage", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_HOSTBANNER("i_needed_modify_power_virtualserver_modify_hostbanner", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_HOSTBUTTON("i_needed_modify_power_virtualserver_modify_hostbutton", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_PORT("i_needed_modify_power_virtualserver_modify_port", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_AUTOSTART("i_needed_modify_power_virtualserver_modify_autostart", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_NEEDED_IDENTITY_SECURITY_LEVEL("i_needed_modify_power_virtualserver_modify_needed_identity_security_level", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_PRIORITY_SPEAKER_DIMM_MODIFICATOR("i_needed_modify_power_virtualserver_modify_priority_speaker_dimm_modificator", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_LOG_SETTINGS("i_needed_modify_power_virtualserver_modify_log_settings", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_MIN_CLIENT_VERSION("i_needed_modify_power_virtualserver_modify_min_client_version", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_ICON_ID("i_needed_modify_power_virtualserver_modify_icon_id", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_WEBLIST("i_needed_modify_power_virtualserver_modify_weblist", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_CODEC_ENCRYPTION_MODE("i_needed_modify_power_virtualserver_modify_codec_encryption_mode", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_TEMPORARY_PASSWORDS("i_needed_modify_power_virtualserver_modify_temporary_passwords", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_TEMPORARY_PASSWORDS_OWN("i_needed_modify_power_virtualserver_modify_temporary_passwords_own", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_CHANNEL_TEMP_DELETE_DELAY_DEFAULT("i_needed_modify_power_virtualserver_modify_channel_temp_delete_delay_default", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_NICKNAME("i_needed_modify_power_virtualserver_modify_nickname", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_MODIFY_INTEGRATIONS("i_needed_modify_power_virtualserver_modify_integrations", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MIN_DEPTH("i_needed_modify_power_channel_min_depth", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MAX_DEPTH("i_needed_modify_power_channel_max_depth", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_GROUP_INHERITANCE_END("i_needed_modify_power_channel_group_inheritance_end", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_PERMISSION_MODIFY_POWER("i_needed_modify_power_channel_permission_modify_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_NEEDED_PERMISSION_MODIFY_POWER("i_needed_modify_power_channel_needed_permission_modify_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_INFO_VIEW("i_needed_modify_power_channel_info_view", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_CHILD("i_needed_modify_power_channel_create_child", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_PERMANENT("i_needed_modify_power_channel_create_permanent", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_SEMI_PERMANENT("i_needed_modify_power_channel_create_semi_permanent", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_TEMPORARY("i_needed_modify_power_channel_create_temporary", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_WITH_TOPIC("i_needed_modify_power_channel_create_with_topic", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_WITH_DESCRIPTION("i_needed_modify_power_channel_create_with_description", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_WITH_PASSWORD("i_needed_modify_power_channel_create_with_password", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_WITH_BANNER("i_needed_modify_power_channel_create_with_banner", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_MODIFY_WITH_CODEC_OPUSVOICE("i_needed_modify_power_channel_create_modify_with_codec_opusvoice", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_MODIFY_WITH_CODEC_OPUSMUSIC("i_needed_modify_power_channel_create_modify_with_codec_opusmusic", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_MODIFY_WITH_CODEC_MAXQUALITY("i_needed_modify_power_channel_create_modify_with_codec_maxquality", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_MODIFY_WITH_CODEC_LATENCY_FACTOR_MIN("i_needed_modify_power_channel_create_modify_with_codec_latency_factor_min", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_WITH_MAXCLIENTS("i_needed_modify_power_channel_create_with_maxclients", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_WITH_MAXFAMILYCLIENTS("i_needed_modify_power_channel_create_with_maxfamilyclients", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_WITH_SORTORDER("i_needed_modify_power_channel_create_with_sortorder", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_WITH_DEFAULT("i_needed_modify_power_channel_create_with_default", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_WITH_NEEDED_TALK_POWER("i_needed_modify_power_channel_create_with_needed_talk_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_MODIFY_WITH_FORCE_PASSWORD("i_needed_modify_power_channel_create_modify_with_force_password", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_CREATE_MODIFY_WITH_TEMP_DELETE_DELAY("i_needed_modify_power_channel_create_modify_with_temp_delete_delay", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_PARENT("i_needed_modify_power_channel_modify_parent", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_MAKE_DEFAULT("i_needed_modify_power_channel_modify_make_default", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_MAKE_PERMANENT("i_needed_modify_power_channel_modify_make_permanent", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_MAKE_SEMI_PERMANENT("i_needed_modify_power_channel_modify_make_semi_permanent", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_MAKE_TEMPORARY("i_needed_modify_power_channel_modify_make_temporary", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_NAME("i_needed_modify_power_channel_modify_name", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_TOPIC("i_needed_modify_power_channel_modify_topic", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_DESCRIPTION("i_needed_modify_power_channel_modify_description", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_PASSWORD("i_needed_modify_power_channel_modify_password", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_BANNER("i_needed_modify_power_channel_modify_banner", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_CODEC("i_needed_modify_power_channel_modify_codec", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_CODEC_QUALITY("i_needed_modify_power_channel_modify_codec_quality", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_CODEC_LATENCY_FACTOR("i_needed_modify_power_channel_modify_codec_latency_factor", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_MAXCLIENTS("i_needed_modify_power_channel_modify_maxclients", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_MAXFAMILYCLIENTS("i_needed_modify_power_channel_modify_maxfamilyclients", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_SORTORDER("i_needed_modify_power_channel_modify_sortorder", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_NEEDED_TALK_POWER("i_needed_modify_power_channel_modify_needed_talk_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_POWER("i_needed_modify_power_channel_modify_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_NEEDED_MODIFY_POWER("i_needed_modify_power_channel_needed_modify_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_MAKE_CODEC_ENCRYPTED("i_needed_modify_power_channel_modify_make_codec_encrypted", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_MODIFY_TEMP_DELETE_DELAY("i_needed_modify_power_channel_modify_temp_delete_delay", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_DELETE_PERMANENT("i_needed_modify_power_channel_delete_permanent", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_DELETE_SEMI_PERMANENT("i_needed_modify_power_channel_delete_semi_permanent", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_DELETE_TEMPORARY("i_needed_modify_power_channel_delete_temporary", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_DELETE_FLAG_FORCE("i_needed_modify_power_channel_delete_flag_force", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_DELETE_POWER("i_needed_modify_power_channel_delete_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_NEEDED_DELETE_POWER("i_needed_modify_power_channel_needed_delete_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_JOIN_PERMANENT("i_needed_modify_power_channel_join_permanent", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_JOIN_SEMI_PERMANENT("i_needed_modify_power_channel_join_semi_permanent", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_JOIN_TEMPORARY("i_needed_modify_power_channel_join_temporary", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_JOIN_IGNORE_PASSWORD("i_needed_modify_power_channel_join_ignore_password", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_JOIN_IGNORE_MAXCLIENTS("i_needed_modify_power_channel_join_ignore_maxclients", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_JOIN_POWER("i_needed_modify_power_channel_join_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_NEEDED_JOIN_POWER("i_needed_modify_power_channel_needed_join_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_SUBSCRIBE_POWER("i_needed_modify_power_channel_subscribe_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_NEEDED_SUBSCRIBE_POWER("i_needed_modify_power_channel_needed_subscribe_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_DESCRIPTION_VIEW_POWER("i_needed_modify_power_channel_description_view_power", ""),
	I_NEEDED_MODIFY_POWER_CHANNEL_NEEDED_DESCRIPTION_VIEW_POWER("i_needed_modify_power_channel_needed_description_view_power", ""),
	I_NEEDED_MODIFY_POWER_ICON_ID("i_needed_modify_power_icon_id", ""),
	I_NEEDED_MODIFY_POWER_MAX_ICON_FILESIZE("i_needed_modify_power_max_icon_filesize", ""),
	I_NEEDED_MODIFY_POWER_ICON_MANAGE("i_needed_modify_power_icon_manage", ""),
	I_NEEDED_MODIFY_POWER_GROUP_IS_PERMANENT("i_needed_modify_power_group_is_permanent", ""),
	I_NEEDED_MODIFY_POWER_GROUP_AUTO_UPDATE_TYPE("i_needed_modify_power_group_auto_update_type", ""),
	I_NEEDED_MODIFY_POWER_GROUP_AUTO_UPDATE_MAX_VALUE("i_needed_modify_power_group_auto_update_max_value", ""),
	I_NEEDED_MODIFY_POWER_GROUP_SORT_ID("i_needed_modify_power_group_sort_id", ""),
	I_NEEDED_MODIFY_POWER_GROUP_SHOW_NAME_IN_TREE("i_needed_modify_power_group_show_name_in_tree", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_SERVERGROUP_LIST("i_needed_modify_power_virtualserver_servergroup_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_SERVERGROUP_PERMISSION_LIST("i_needed_modify_power_virtualserver_servergroup_permission_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_SERVERGROUP_CLIENT_LIST("i_needed_modify_power_virtualserver_servergroup_client_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CHANNELGROUP_LIST("i_needed_modify_power_virtualserver_channelgroup_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CHANNELGROUP_PERMISSION_LIST("i_needed_modify_power_virtualserver_channelgroup_permission_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CHANNELGROUP_CLIENT_LIST("i_needed_modify_power_virtualserver_channelgroup_client_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CLIENT_PERMISSION_LIST("i_needed_modify_power_virtualserver_client_permission_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CHANNEL_PERMISSION_LIST("i_needed_modify_power_virtualserver_channel_permission_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CHANNELCLIENT_PERMISSION_LIST("i_needed_modify_power_virtualserver_channelclient_permission_list", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_SERVERGROUP_CREATE("i_needed_modify_power_virtualserver_servergroup_create", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CHANNELGROUP_CREATE("i_needed_modify_power_virtualserver_channelgroup_create", ""),
	I_NEEDED_MODIFY_POWER_GROUP_MODIFY_POWER("i_needed_modify_power_group_modify_power", ""),
	I_NEEDED_MODIFY_POWER_GROUP_NEEDED_MODIFY_POWER("i_needed_modify_power_group_needed_modify_power", ""),
	I_NEEDED_MODIFY_POWER_GROUP_MEMBER_ADD_POWER("i_needed_modify_power_group_member_add_power", ""),
	I_NEEDED_MODIFY_POWER_GROUP_NEEDED_MEMBER_ADD_POWER("i_needed_modify_power_group_needed_member_add_power", ""),
	I_NEEDED_MODIFY_POWER_GROUP_MEMBER_REMOVE_POWER("i_needed_modify_power_group_member_remove_power", ""),
	I_NEEDED_MODIFY_POWER_GROUP_NEEDED_MEMBER_REMOVE_POWER("i_needed_modify_power_group_needed_member_remove_power", ""),
	I_NEEDED_MODIFY_POWER_PERMISSION_MODIFY_POWER("i_needed_modify_power_permission_modify_power", ""),
	I_NEEDED_MODIFY_POWER_PERMISSION_MODIFY_POWER_IGNORE("i_needed_modify_power_permission_modify_power_ignore", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_SERVERGROUP_DELETE("i_needed_modify_power_virtualserver_servergroup_delete", ""),
	I_NEEDED_MODIFY_POWER_VIRTUALSERVER_CHANNELGROUP_DELETE("i_needed_modify_power_virtualserver_channelgroup_delete", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_PERMISSION_MODIFY_POWER("i_needed_modify_power_client_permission_modify_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_NEEDED_PERMISSION_MODIFY_POWER("i_needed_modify_power_client_needed_permission_modify_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_MAX_CLONES_UID("i_needed_modify_power_client_max_clones_uid", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_MAX_IDLETIME("i_needed_modify_power_client_max_idletime", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_MAX_AVATAR_FILESIZE("i_needed_modify_power_client_max_avatar_filesize", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_MAX_CHANNEL_SUBSCRIPTIONS("i_needed_modify_power_client_max_channel_subscriptions", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_IS_PRIORITY_SPEAKER("i_needed_modify_power_client_is_priority_speaker", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_SKIP_CHANNELGROUP_PERMISSIONS("i_needed_modify_power_client_skip_channelgroup_permissions", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_FORCE_PUSH_TO_TALK("i_needed_modify_power_client_force_push_to_talk", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_IGNORE_BANS("i_needed_modify_power_client_ignore_bans", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_IGNORE_ANTIFLOOD("i_needed_modify_power_client_ignore_antiflood", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_USE_RESERVED_SLOT("i_needed_modify_power_client_use_reserved_slot", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_USE_CHANNEL_COMMANDER("i_needed_modify_power_client_use_channel_commander", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_REQUEST_TALKER("i_needed_modify_power_client_request_talker", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_AVATAR_DELETE_OTHER("i_needed_modify_power_client_avatar_delete_other", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_IS_STICKY("i_needed_modify_power_client_is_sticky", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_IGNORE_STICKY("i_needed_modify_power_client_ignore_sticky", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_INFO_VIEW("i_needed_modify_power_client_info_view", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_PERMISSIONOVERVIEW_VIEW("i_needed_modify_power_client_permissionoverview_view", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_PERMISSIONOVERVIEW_OWN("i_needed_modify_power_client_permissionoverview_own", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_REMOTEADDRESS_VIEW("i_needed_modify_power_client_remoteaddress_view", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_SERVERQUERY_VIEW_POWER("i_needed_modify_power_client_serverquery_view_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_NEEDED_SERVERQUERY_VIEW_POWER("i_needed_modify_power_client_needed_serverquery_view_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_CUSTOM_INFO_VIEW("i_needed_modify_power_client_custom_info_view", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_KICK_FROM_SERVER_POWER("i_needed_modify_power_client_kick_from_server_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_NEEDED_KICK_FROM_SERVER_POWER("i_needed_modify_power_client_needed_kick_from_server_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_KICK_FROM_CHANNEL_POWER("i_needed_modify_power_client_kick_from_channel_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_NEEDED_KICK_FROM_CHANNEL_POWER("i_needed_modify_power_client_needed_kick_from_channel_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_BAN_POWER("i_needed_modify_power_client_ban_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_NEEDED_BAN_POWER("i_needed_modify_power_client_needed_ban_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_MOVE_POWER("i_needed_modify_power_client_move_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_NEEDED_MOVE_POWER("i_needed_modify_power_client_needed_move_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_COMPLAIN_POWER("i_needed_modify_power_client_complain_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_NEEDED_COMPLAIN_POWER("i_needed_modify_power_client_needed_complain_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_COMPLAIN_LIST("i_needed_modify_power_client_complain_list", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_COMPLAIN_DELETE_OWN("i_needed_modify_power_client_complain_delete_own", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_COMPLAIN_DELETE("i_needed_modify_power_client_complain_delete", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_BAN_LIST("i_needed_modify_power_client_ban_list", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_BAN_CREATE("i_needed_modify_power_client_ban_create", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_BAN_DELETE_OWN("i_needed_modify_power_client_ban_delete_own", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_BAN_DELETE("i_needed_modify_power_client_ban_delete", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_BAN_MAX_BANTIME("i_needed_modify_power_client_ban_max_bantime", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_PRIVATE_TEXTMESSAGE_POWER("i_needed_modify_power_client_private_textmessage_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_NEEDED_PRIVATE_TEXTMESSAGE_POWER("i_needed_modify_power_client_needed_private_textmessage_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_SERVER_TEXTMESSAGE_SEND("i_needed_modify_power_client_server_textmessage_send", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_CHANNEL_TEXTMESSAGE_SEND("i_needed_modify_power_client_channel_textmessage_send", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_OFFLINE_TEXTMESSAGE_SEND("i_needed_modify_power_client_offline_textmessage_send", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_TALK_POWER("i_needed_modify_power_client_talk_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_NEEDED_TALK_POWER("i_needed_modify_power_client_needed_talk_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_POKE_POWER("i_needed_modify_power_client_poke_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_NEEDED_POKE_POWER("i_needed_modify_power_client_needed_poke_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_SET_FLAG_TALKER("i_needed_modify_power_client_set_flag_talker", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_WHISPER_POWER("i_needed_modify_power_client_whisper_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_NEEDED_WHISPER_POWER("i_needed_modify_power_client_needed_whisper_power", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_MODIFY_DESCRIPTION("i_needed_modify_power_client_modify_description", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_MODIFY_OWN_DESCRIPTION("i_needed_modify_power_client_modify_own_description", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_MODIFY_DBPROPERTIES("i_needed_modify_power_client_modify_dbproperties", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_DELETE_DBPROPERTIES("i_needed_modify_power_client_delete_dbproperties", ""),
	I_NEEDED_MODIFY_POWER_CLIENT_CREATE_MODIFY_SERVERQUERY_LOGIN("i_needed_modify_power_client_create_modify_serverquery_login", ""),
	I_NEEDED_MODIFY_POWER_FT_IGNORE_PASSWORD("i_needed_modify_power_ft_ignore_password", ""),
	I_NEEDED_MODIFY_POWER_FT_TRANSFER_LIST("i_needed_modify_power_ft_transfer_list", ""),
	I_NEEDED_MODIFY_POWER_FT_FILE_UPLOAD_POWER("i_needed_modify_power_ft_file_upload_power", ""),
	I_NEEDED_MODIFY_POWER_FT_NEEDED_FILE_UPLOAD_POWER("i_needed_modify_power_ft_needed_file_upload_power", ""),
	I_NEEDED_MODIFY_POWER_FT_FILE_DOWNLOAD_POWER("i_needed_modify_power_ft_file_download_power", ""),
	I_NEEDED_MODIFY_POWER_FT_NEEDED_FILE_DOWNLOAD_POWER("i_needed_modify_power_ft_needed_file_download_power", ""),
	I_NEEDED_MODIFY_POWER_FT_FILE_DELETE_POWER("i_needed_modify_power_ft_file_delete_power", ""),
	I_NEEDED_MODIFY_POWER_FT_NEEDED_FILE_DELETE_POWER("i_needed_modify_power_ft_needed_file_delete_power", ""),
	I_NEEDED_MODIFY_POWER_FT_FILE_RENAME_POWER("i_needed_modify_power_ft_file_rename_power", ""),
	I_NEEDED_MODIFY_POWER_FT_NEEDED_FILE_RENAME_POWER("i_needed_modify_power_ft_needed_file_rename_power", ""),
	I_NEEDED_MODIFY_POWER_FT_FILE_BROWSE_POWER("i_needed_modify_power_ft_file_browse_power", ""),
	I_NEEDED_MODIFY_POWER_FT_NEEDED_FILE_BROWSE_POWER("i_needed_modify_power_ft_needed_file_browse_power", ""),
	I_NEEDED_MODIFY_POWER_FT_DIRECTORY_CREATE_POWER("i_needed_modify_power_ft_directory_create_power", ""),
	I_NEEDED_MODIFY_POWER_FT_NEEDED_DIRECTORY_CREATE_POWER("i_needed_modify_power_ft_needed_directory_create_power", ""),
	I_NEEDED_MODIFY_POWER_FT_QUOTA_MB_DOWNLOAD_PER_CLIENT("i_needed_modify_power_ft_quota_mb_download_per_client", ""),
	I_NEEDED_MODIFY_POWER_FT_QUOTA_MB_UPLOAD_PER_CLIENT("i_needed_modify_power_ft_quota_mb_upload_per_client", "");

	private final String name;
	private final String description;

	IPermissionType(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public String getName() {
		return name;
	}

	public String getDescription() {
		return description;
	}

}
